### ISSUE TITLE
Feature Request: Html file generated from large twitter archive can't be loaded by browser

### ISSUE THREAD

**Issue by martinbrook** [timhutton/twitter-archive-parser#103]
After processing my archive I ended up with 

4048380 Nov 22 22:30  TweetArchive.html

which chrome refused to load.

An option to split by month or year might be useful.

Note: firefox was able to consume the file

**Comment by timhutton** [comment]
Thanks @martinbrook. Yes we should split them the same way we split the md files. It could even use the same code.
