### ISSUE TITLE
Needed: embed images, videos in DMs

### ISSUE THREAD

**Issue by timhutton** [timhutton/twitter-archive-parser#106]
We embed images and videos in tweets. The exact same thing should be possible in the *.md and *.html output that contains the DMs (and, pending other work, the group DMs).

**Comment by flauschzelle** [comment]
(Markdown only) maybe solved in #116

**Comment by flauschzelle** [comment]
Done for markdown in #116. There's a separate Issue for HTML output of DMs, so I think this can be closed now.
