### ISSUE TITLE
Suggestion re embedded video

### ISSUE THREAD

**Issue by n1vux** [timhutton/twitter-archive-parser#108]
The captions for embedded video (often MP3 converted from GIF) is generally some variant of `Your Browser doesn't support Video`

For any GIF that has ALT text attached, the ALT text could be used as Meta Data to become the caption of the video tag? IDK if that's available in the API you're using. (Same could be applied to JPG, PNG if it works?)

(I don't need this, just suggesting. I just went through and replaced the error text with a reasonable caption for each MP4 video. As expected, "Why not Both?" is my most used GIF. It was an amusing walk through history.)

Anyway, thank you! A MarkDown file per month etc is much more useful archival format.

**Comment by timhutton** [comment]
Is the text in the content of a video tag the ALT text? I thought that was just fallback for if videos aren't supported.

I guess the answer will be: whatever screen-readers do with video tags. Does anyone know?

I see discussion here of using the title="" attribute:
https://discuss.codecademy.com/t/can-we-use-an-alt-attribute-with-the-video-tag/300322/13
but that seems unofficial.

And here a suggestion to indeed put the ALT text in the video tag content:
https://stackoverflow.com/questions/32129240/html5-video-element-alternative-text

Do GIF files often have ALT text in them? (I knew they can have a message in but not that it gets used for ALT text.)

There's a related issue about ALT tags here: #20

**Comment by n1vux** [comment]
On Wed, Nov 23, 2022 at 2:44 PM Tim Hutton ***@***.***> wrote:

> Is the text in the content of a video tag the ALT text? I thought that was
> just fallback for if videos aren't supported.
>
Aha!  Yes, you're right.  So the CONTENT is the wrong place for title or
ALT text (although perhaps not a bad place to repeat it).
At this point, i assume someone using a browser that doesn't support
<video> is aware of that, is doing so intentionally, and doesn't need every
<video> tag to expand to it.

I guess the answer will be: whatever screen-readers do with video tags.
> Does anyone know?
>
Excellent question.
(Modern Screen-readers work with browsers that support <video> so CONTENT
isn't useful for the primary use of ALT.)

ALT is useful even for sighted users w/ Twitter and GIF, for those of us
uncool enough to not recognize what movie/TV/... the GIF is from.

I'm not sure if GIF have ALT *in  *them as Meta Data (which would be Good!)
or if ALT if applied by one users is remembered by Twitter, but i'm
starting to see GIFs with ALT before i add one.

**Comment by timhutton** [comment]
Closing this pending clarity on whether `<video>` tags can even have ALT text, and some way of obtaining the text for Twitter videos. I think the correct answer is that the closed captions are intended to solve this problem, which is out of scope for this project.
