### ISSUE TITLE
'tweet_media' and 'tweets_media' folders

### ISSUE THREAD

**Issue by adikeinan** [timhutton/twitter-archive-parser#124]
Hello there! I've been having this issue with the script: when I run it, after a couple of seconds it throws this error message:
`Error: no folders matching ['tweet_media', 'tweets_media'] in .\data`
I do have a 'tweets_media' folder under ‘data’, but not ‘tweet_media'.
Could you please advise? Thanks!

**Comment by lenaschimmel** [comment]
Hi! You probably called the script from another folder. You have to be inside the archive folder and call the script from there.

(The script should give a more helpful error message in that case, which will be fixed by the PR @flauschzelle just made.)

**Comment by mialondon** [comment]
I just did a pull request on the readme to add an additional 'change into the unzipped directory' step to the process, just to make it easier to spot that.

**Comment by mialondon** [comment]
(But it may not be needed if there's an error message fix on the way!)

**Comment by flauschzelle** [comment]
I think it doesn't hurt to also make it clearer in the readme, even when there is a better error message again. Especially because you've already done the work and it just needs merging :)

**Comment by adikeinan** [comment]
> Hi! You probably called the script from another folder. You have to be inside the archive folder and call the script from there.
> 
> (The script should give a more helpful error message in that case, which will be fixed by the PR @flauschzelle just made.)

Thank you! That worked.
