### ISSUE TITLE
[Suggestion] In the instructions for use, may I suggest an addition to the fourth line?

### ISSUE THREAD

**Issue by TheSupercargo** [timhutton/twitter-archive-parser#136]
4. Run parser.py with Python 3. e.g. python parser.py from a command prompt opened in that folder. [Addition] _In Windows, this means you need to open Windows Powershell in the same folder where the Twitter archive is unzipped. Hold shift while right clicking in the folder. Click on Open PowerShell. When the command window opens, paste or enter "python parser.py" at the command prompt._ 

I suggest this because it took me a day to work out what this instruction was telling me to do. I kept trying to right click the parser.py file and open it in Python or try to open the main command prompt and type in the address for parser.py . Probably this seems really dumb to programmers, but I suggest most of the people who might want to use this programme right now will have as little experience of writing code as I have. Or less. 

Once I'd worked out how to open it, parser.py wrked like a dream!

**Comment by flauschzelle** [comment]
Fixed in #138, thanks for the suggestion :)
