### ISSUE TITLE
Feature Request: Chronological Folders

### ISSUE THREAD

**Issue by nitinpai007** [timhutton/twitter-archive-parser#14]
It will be great if the tweets are output in nested chronological folders The folders can be in the format YYYY and MM, with a DD.md containing all the tweets on the day. 
Eg
2022
     |__01
            |__01.md 
            |__02.md
            ...
            |__31.md 
     ...
 2021
      |__01
            |__01.md 
            |__02.md
            ...
            |__31.md 

 
This will make it easier to publish the entire archive on a website.

**Comment by timhutton** [comment]
Yes, nice. I was just writing up a similar proposal: #15
