### ISSUE TITLE
404's on image retrieval?

### ISSUE THREAD

**Issue by scottjenson** [timhutton/twitter-archive-parser#149]
Trying to run this for the first time today 5 Dec 2022 and I'm getting LOT of these logs:

    64.4 % done, about 1 hour 57 minutes remaining...
    718/1113 .\parser-output\media\792819897990455296-CwCpdwhVIAAmWnb.jpg: Requesting headers for https://pbs.twimg.com/medi718/1113 .\parser-output\media\792819897990455296-CwCpdwhVIAAmWnb.jpg: FAIL. Media couldn't be retrieved from https://pbs.twimg.com/media/CwCpdwhVIAAmWnb.jpg:orig because of exception: Download failed with status "404 Not Found". Response content: ""

It's going to take ~4 hours to run and I'm just letting it go. The parser-output/media folder is full of images so things appear to be working. Is this working-as-intended or just a very confusing LOG ouput?

**Comment by scottjenson** [comment]
Figured it out. I had protected my account. I didn't realize this would affect the download. I did get a helpful message at the end of the script that helped me figure it out. Maybe offer this at the beginning?

**Comment by timhutton** [comment]
@scottjenson Thanks for updating us. Others might find this issue and be helped.

There is a message before the downloads but easy to miss:

```
    print(f"\nThe archive doesn't contain the original-size images. We can attempt to download them from twimg.com.")
    print(f'Please be aware that this script may download a lot of data, which will cost you money if you are')
    print(f'paying for bandwidth. Please be aware that the servers might block these requests if they are too')
    print(f'frequent. This script may not work if your account is protected. You may want to set it to public')
    print(f'before starting the download.\n')
```

**Comment by haikusw** [comment]
I missed this message also and am getting the same issue.  
I'd suggest adding a pause with prompt to continue in the script.

Thank you very much for this script!

**Comment by haikusw** [comment]
Definitely blocking my requests.  My twitter account isn't protected. Will try increasing timeout.
