### ISSUE TITLE
Split output into separate files

### ISSUE THREAD

**Issue by timhutton** [timhutton/twitter-archive-parser#15]
Motivations:
1. Enormous markdown files cause problems for rendering.
2. Import into Jekyll etc needs separate files.

Proposal:
- Construct a filename using the timestamp
- Output each tweet as a separate markdown file

**Comment by rossgrady** [comment]
I have 170k tweets in my archive (whee!) so I'd be interested in some actual controls around the splits (daily / weekly / monthly / annually) because 170k individual markdown files probably (for me) trades one problem for another :)

**Comment by rossgrady** [comment]
Incredibly naive implementation by someone for whom Python is not a fluent language, which is why I'm not submitting this as a PR (commented lines for quick orientation to where this sits in `main()`):

```
    # tweets_markdown = [md for t,md in tweets_markdown] # discard timestamps
    global lastyear
    global all_tweets
    lastyear = 2009
    all_tweets = ""
    for t,md in tweets_markdown:
        dt = datetime.datetime.fromtimestamp(t)
        currentyear = dt.year
        if (currentyear == lastyear):
            all_tweets += '\n----\n'+md
        else:
            output_filename = str(lastyear)+'.md'
            print('writing out to ' + output_filename)
            with open(output_filename, 'w', encoding='utf-8') as f:
                f.write(all_tweets)
            all_tweets = '\n----\n'+md
            lastyear = currentyear


    # Save as one large markdown file
    # all_tweets = '\n----\n'.join(tweets_markdown)
    # with open(output_filename, 'w', encoding='utf-8') as f:
    #    f.write(all_tweets)
    # print(f'Wrote to {output_filename}, which embeds images from {output_media_folder_name}')
```

**Comment by rossgrady** [comment]
(proof that I should not be trusted is that the above will not write out the final year's file, LOL)

It otherwise does what I want, though!

**Comment by rossgrady** [comment]
Last comment on this issue: I forked & made the changes (& fixed my dumbness) and it seems to work. Not going to open a PR (still) because I don't know whether/how you hoped to implement this -- I went with discrete files per YYYY-MM: https://github.com/rossgrady/twitter-archive-parser

**Comment by timhutton** [comment]
Make a PR. It sounds like a sensible default to me.

**Comment by rossgrady** [comment]
OK! 

https://github.com/timhutton/twitter-archive-parser/pull/24
