### ISSUE TITLE
Feature request: Download full-size images from Twitter

### ISSUE THREAD

**Issue by timhutton** [timhutton/twitter-archive-parser#16]
@masukomi points out in #13 that the images in the Twitter archive are not the original size.

Example: an image in my archive is 600x809. If I download from Twitter appending `?format=jpg&name=large` then it gives me an image that is 780x1052.

Conceivably we could automate the downloading of full size images.

**Comment by cooljeanius** [comment]
According to the @archiveteam wiki appending `:orig` to the image URL has the same effect, but I dunno how up-to-date that info is: https://wiki.archiveteam.org/index.php/Twitter

**Comment by timhutton** [comment]
What I'm thinking at the moment for this:

- We make a separate script `download_better_images.py`
- After `parser.py` we print a message saying that they might be able to get slightly higher-resolution images by running the other script - if their account is still active, and twitter.com is still available, and if they are willing to wait for it and pay for the bandwidth, and risk gettting blocked by twitter for hammering their servers.
-  The download script looks through the `media/` folder for `<tweet_id>_<media_id>.<ext>` files and attempts to download them from `https://pbs.twimg.com/media/<media_id>.<ext>:orig` If it succeeds then it overwrites the file in `media/`

Thoughts?
