### ISSUE TITLE
Unable to run - SyntaxError: invalid character '·' (U+00B7)

### ISSUE THREAD

**Issue by andrewbaker-uk** [timhutton/twitter-archive-parser#17]
Using python parser.py with Python 3.10.6 the command fails with the error 

```
> abaker@Andrew-PC:~/Twitter$ python parser.py
>   File "/home/abaker/Twitter/parser.py", line 70
>     <title>twitter-archive-parser/parser.py at main · timhutton/twitter-archive-parser · GitHub</title>
>                                                     ^
> SyntaxError: invalid character '·' (U+00B7)
> abaker@Andrew-PC:~/Twitter$ ll
> total 21288
> drwxr-x---+  4 abaker abaker     4096 Nov 11 15:52  ./
> drwxr-x---+  3 abaker abaker     4096 Nov 11 15:49  ../
> -rw-rw-r--   1 abaker abaker     1432 Nov 10 23:30 'Your archive.html'
> drw-rw-r--+  5 abaker abaker     4096 Nov 10 23:30  assets/
> drw-rw-r--+ 11 abaker abaker     4096 Nov 10 23:30  data/
> -rw-rw-r--   1 abaker abaker   208979 Nov 11 15:48  parser.py
> -rw-rw-r--   1 abaker abaker 21561802 Nov 10 23:33  twitter-2022-11-10-fe53538580a484bb0e4a4af7c4b36c493b6815a9a9bc28e02b33a82f31eda3b3.zip
> abaker@Andrew-PC:~/Twitter$ python --version
> Python 3.10.6
```

**Comment by timhutton** [comment]
Looks like you have downloaded not parser.py but the html page that was showing parser.py. Try [this link](https://raw.githubusercontent.com/timhutton/twitter-archive-parser/main/parser.py) instead - with "right-click save target as" or whatever is appropriate for your platform. Or open that link and do "right-click save page as".

**Comment by andrewbaker-uk** [comment]
D'oh thanks. I did `wget https://github.com/timhutton/twitter-archive-parser/blob/main/parser.py` instead of `wget https://raw.githubusercontent.com/timhutton/twitter-archive-parser/main/parser.py`

**Comment by timhutton** [comment]
@ek6891 The link in `How do I use it?` should be correct - it points to the 'raw' version.

I think the problem happens when people right-click on the link in the code list at the top of the page.

Please let me know how the instructions could be clearer. Maybe I need to explicitly say that one link is good and the other bad.

**Comment by Steve677067** [comment]
Unsubscribe to the. Link please and thank you for your understanding

**Comment by andrewbaker-uk** [comment]
@timhutton I have slightly altered the wording on the instructions. Other than placing it in big flashing neon signs, can't help people not reading the instructions :)

**Comment by timhutton** [comment]
The error message this gives for the current script, reported by another user recently:

```
File "./parser.py", line 8
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```

I'll change the title to reflect this.
