### ISSUE TITLE
Better filename for sorting (and Jekyll ;)

### ISSUE THREAD

**Issue by jwildeboer** [timhutton/twitter-archive-parser#35]
I changed line 135

` filename = f'tweets_{dt.year}-{dt.month:02}.md'`

to

`
filename = f'{dt.year}-{dt.month:02}-01-Tweet-Archive-{dt.year}-{dt.month:02}.md'
`

To get nicer filenames that I can just throw in a Jekyll _posts directory to start creating nice looking pages.

Not sure if this is worthy of a PR, maybe just a FYI or an idea :)

**Comment by timhutton** [comment]
Oh, Jekyll needs `YYYY-MM-DD-your-title-is-here.md` otherwise it doesn't work. I probably knew that once and forgot.

Yes, we should do that. Even as a default for non-Jekyll users it is tolerable I think.

If you want one tweet per Jekyll post then this might work:

`filename = f'{dt.year}-{dt.month:02}-01-Tweet-Archive-{dt.year}-{dt.month:02}-{timestamp}.md'`

I can't think of a better way of making a suitable title for each post.

**Comment by jwildeboer** [comment]
That would be 102917 Jekyll posts in my case - Please no ;) One file per month is good enough for me.

**Comment by jwildeboer** [comment]
Works :) Thank you and closing issue! FTR: It took around 35 seconds to go through my 2.7GB archive and generate 169 .md files containing 102917 tweets with 15926 media files referenced. It took Jekyll 21 seconds to generate a website with static files from that. Nice!

**Comment by timhutton** [comment]
It's not merged yet.

**Comment by timhutton** [comment]
@jwildeboer Question about the output folder for the images and videos:

After changing the media folder to `images/` do all the image and videos work in Jekyll?

(My Jekyll folder is called `assets/`, not sure if I did that.)

**Comment by jwildeboer** [comment]
Yes, with my current simple Jekyll setup I can get it to work by search and replacing all `(images/` in the output with `(/images/` as without the leading `/` jekyll tries relative paths, which fail. After this search and replace it all works more or less out of the box.

I admit, I am too tired right now (1 am, Munich, Germany) to find a better solution but will do some more checks tomorrow.

**Comment by timhutton** [comment]
Thanks! Good to know. I haven't tried mine yet.

A question for tomorrow, and off-topic:

Do you know of a client-side rendered version of Jekyll? It would retrieve a list of md files then retrieve each one when it was time to show it. I'm so sick of the setup I need to do every time I need to add a post to my blog.

**Comment by jwildeboer** [comment]
If you use vs code/vscodium, there is a Jekyll plugin/extension which might help. I have a local Jekyll install on my machine, so I just run a `bundle exec jekyll serve --future --unpublished` in whatever directory with the minimal files.

**Comment by jwildeboer** [comment]
(and I also have a CI pipeline on codeberg.org where I host my blog and various other sites, so whenever I am done I just commit and let the CI pipeline handle the rest ;)
