### ISSUE TITLE
Bug: markdown inside tweets is not escaped

### ISSUE THREAD

**Issue by twoscomplement** [timhutton/twitter-archive-parser#40]
Consider https://twitter.com/twoscomplement/status/1580380783767756801 - note the text \_\_VA_ARGS\_\_

The tweet body text is copied verbatim by parser.py, resulting in __VA_ARGS__ when the markdown is rendered
![image](https://user-images.githubusercontent.com/7036678/201547412-21ad111b-8aa1-4b1b-9c5b-f04f685be171.png)

**Comment by timhutton** [comment]
Another example:

`We previously made a smaller version out of cardboard: https://mobile.twitter.com/_tim_hutton_/status/1010638114417766400`

The underscores break the URL:

![image](https://user-images.githubusercontent.com/647092/201675042-b2e28909-305f-4a75-a5dd-fe8577ddaa87.png)

**Comment by flauschzelle** [comment]
I haven't actually tried it yet, but here's at least a hint to start with:  
This could probably be solved by using something similar to [this example](https://github.com/python-telegram-bot/python-telegram-bot/blob/9520c6eeba8d1332c6080134f042d338948a47a2/telegram/helpers.py#L44) (@lenaschimmel did a quick research and found this) somewhere inside the [convert_tweet method](https://github.com/timhutton/twitter-archive-parser/blob/main/parser.py#L62).

**Comment by flauschzelle** [comment]
Related, but only for DMs: #117
