### ISSUE TITLE
Invalid character error

### ISSUE THREAD

**Issue by ek6891** [timhutton/twitter-archive-parser#56]
Using the current script and the image script returns the following error in cmd for line 70:

`<title>twitter-archive-parser/parser.py at main · timhutton/twitter-archive-parser · GitHub</title>
                                                    ^
SyntaxError: invalid character '·' (U+00B7)`

The middle dot (U+00B7) needs to be replaced.

**Comment by timhutton** [comment]
For people who hit this error: Duplicates #17

**Comment by Steve677067** [comment]
Please excuse me I am truly sorry for the misunderstanding
