### ISSUE TITLE
"Media couldn't be retrieved" on download_better_images

### ISSUE THREAD

**Issue by kasamikona** [timhutton/twitter-archive-parser#69]
When running download_better_images.py, about half of the results (randomly) are outputting "Fail. Media couldn't be retrieved". The given URLs with :orig appended are working fine in my browser. There doesn't appear to be any pattern.

**Comment by kasamikona** [comment]
I added logging and it's hitting "[WinError 183] Cannot create a file when that file already exists" when trying to rename the new .tmp downloaded file to the old file. I'm not sure why it works sometimes and not other times, but perhaps the old file should first be explicitly deleted first.

**Comment by timhutton** [comment]
Oh! Good catch. thanks @kasamikona. I will fix that now.

**Comment by timhutton** [comment]
@kasamikona Can you confirm that it works better now?

**Comment by kasamikona** [comment]
Made the exact same change to my local copy and it's running fine now, aside from the odd fail from twitter's end which will probably get caught with a second pass.

**Comment by timhutton** [comment]
Thanks. Current events at twitter are suddenly making it more important that this code works!
