### ISSUE TITLE
Expand t.co URLs for all links 

### ISSUE THREAD

**Issue by timhutton** [timhutton/twitter-archive-parser#9]

**Comment by Atari-Frosch** [comment]
I don't know whether this is what you meant, but I have written a script that can expand the URIs from at least some URL shorteners by, well, just asking them. I have no experience in contributing to someone else's project, so I guess the best way is that I pass you the files. :-) 
[shorturls.zip](https://github.com/timhutton/twitter-archive-parser/files/9987174/shorturls.zip)

**Comment by timhutton** [comment]
I looked into this issue. All remaining t.co links are in retweets (`RT:`). Many of them are truncated because the archive doesn't include the full text of retweets but cuts it off with an ellipsis. I don't think we can usefully do anything here.

**Comment by timhutton** [comment]
@Atari-Frosch It wasn't what I meant but there is a need to get rid of shortened URLs generally, and now a PR to do it (#42) based on your code.
